/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DragDemoRouteImport } from './routes/drag-demo'
import { Route as EcgRouteImport } from './routes/ecg'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DragDemoRoute = DragDemoRouteImport.update({
  id: '/drag-demo',
  path: '/drag-demo',
  getParentRoute: () => rootRouteImport,
} as any)
const EcgRoute = EcgRouteImport.update({
  id: '/ecg',
  path: '/ecg',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/drag-demo': typeof DragDemoRoute
  '/ecg': typeof EcgRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/drag-demo': typeof DragDemoRoute
  '/ecg': typeof EcgRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/drag-demo': typeof DragDemoRoute
  '/ecg': typeof EcgRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/drag-demo' | '/ecg'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/drag-demo' | '/ecg'
  id: '__root__' | '/' | '/drag-demo' | '/ecg'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DragDemoRoute: typeof DragDemoRoute
  EcgRoute: typeof EcgRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/drag-demo': {
      id: '/drag-demo'
      path: '/drag-demo'
      fullPath: '/drag-demo'
      preLoaderRoute: typeof DragDemoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ecg': {
      id: '/ecg'
      path: '/ecg'
      fullPath: '/ecg'
      preLoaderRoute: typeof EcgRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DragDemoRoute: DragDemoRoute,
  EcgRoute: EcgRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
